### ISSUE TITLE
The suggestEntityCandidates endpoint crashes with array index out of bounds Exception.

### ISSUE THREAD

**Issue by jkrumow** [dkt-projekt/e-NLP#11]
`curl -X POST -d @746ef85be1dab5f24875eb6e7ca8d5eb.txt "http://api.digitale-kuratierung.de/api/e-nlp/suggestEntityCandidates?language=en&threshold=0.1" --header "Content-Type: text/plain"`

```
{
  "exception": "java.lang.ArrayIndexOutOfBoundsException",
  "path": "/e-nlp/suggestEntityCandidates",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1474538871883
}
```

I could provide you with the file that I have used.

**Comment by PeterBourgonje** [comment]
Thanks for the feedback. If you could send me the file that would be great.

**Comment by jkrumow** [comment]
Sent.

**Comment by PeterBourgonje** [comment]
Thanks. Fixed on the dev version now. Will be available after the next release on the live server. FYI (we will also communicate this in the next consortium call), we postponed the release to a later date (probably October 19th), because of the #DKT16 conference

**Comment by jkrumow** [comment]
Helle Peter,

it's too bad that you have postponed the release since we are using the endpoint in our demonstrator we will show on the #DKT16 conference.

**Comment by PeterBourgonje** [comment]
The dev server is hosting the new version, where the bug is fixed. As a workaround, we can make sure that we don't touch the dev server a couple of days before/during the #DKT16 conference, so that this should be up and running and stable for your demo-ing purposes. Would that be ok with you?

**Comment by jkrumow** [comment]
ok. sounds good.
