### ISSUE TITLE
Concurrent access fails

### ISSUE THREAD

**Issue by jnehring** [dkt-projekt/e-NLP#3]
Try this shell script (download [data.txt](https://github.com/dkt-projekt/e-NLP/files/263194/data.txt) before)

```
for i in {1..4}
do
    curl -X POST -d @data.txt --header "Content-Type: text/plain" "http://api.digitale-kuratierung.de/api/e-nlp/namedEntityRecognition?language=en&analysis=ner&models=ner-wikinerEn_LOC&informat=text&outformat=turtle&link=no" > $i &

done
```

The script creates 4 API requests at almost the same time and stores the results in text files named 1,2,3 and 4. Request 1 is successful, 2,3,4 fail with "Internal server error". I guess there is a problem with concurrent access to the API.

This is a blocker for the cloud experiment.

**Comment by jox** [comment]
There are two problems here. They are both related to data that is stored in static member variables.

1. The class `de.dkt.eservices.eopennlp.modules.NameFinder` stores its pre-loaded models of type `opennlp.tools.namefind.NameFinderME` in a static member variable named `nameFinderPreLoadedModels`. However, `NameFinderME.find()` is not thread-save, but it is called concurrently on the same instance of `NameFinderME`. 

2. The class `Sparqler` stores its state in static members between calls to the (static) methods `Sparqler.queryDBPedia()` and `Sparqler.addGeoStats()`. This makes it non-thread-safe. In concurrent calls the state gets mixed up.

They can be fixed as follows:

1. Synchronize the calls to `NameFinderME.find()` by locking the call to the affected `NameFinderME` instance.

2. Change the design of the `Sparqler` class to use a local instance of it that has a local thread-scoped state. This can be done by simply making the state variables and the methods non-static (and of course adjusting the code that makes use of these methods).

I've tested that with the shell script above and it now runs with the expected results. I'll create a pull request.

Note that these are problems in this specific case. There might be other concurrency issues elsewhere. More concurrency testing would have to be done.

**Comment by jnehring** [comment]
Thank you @jox!

I merged this branch in the master. I tested it locally and it works fine. The feature is not yet deployed on the live server but I guess it is fixed.
