### ISSUE TITLE
NullPointerExcpetion when parameters are wrong

### ISSUE THREAD

**Issue by jnehring** [dkt-projekt/e-NLP#7]
I tried to integrate e-NLP in an example pipeline while working on dkt-projekt/DktBrokerStandalone#5 . This API request

```
curl -X POST -H "Cache-Control: no-cache" -H "Postman-Token: e3a20750-8dd5-8b72-4cff-c8cdedb7b26b" -d 'This summer there is the Zomerbar in Antwerp, one of the most beautiful cities in Belgium.' "http://dev.digitale-kuratierung.de/api/e-nlp/namedEntityRecognition?language=en&analysis=ner-wikinerEn_LOC&informat=text"
```

fails with

```
{
  "exception": "java.lang.NullPointerException",
  "path": "/e-nlp/namedEntityRecognition",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1470126523407
}
```

I think the problem is that I did not specify a model and I did specify an invalid value for analysis. However this should lead to error 400 - Bad Request and not this error.

**Comment by PeterBourgonje** [comment]
Thanks for spotting! Fixed it. Please try again and verify.

**Comment by jnehring** [comment]
Fixed! That was a quick bugfixing :)
